import Navbar from "@/components/Navbar";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { AuthContextProvider } from "@/app/context/AuthContext";

const font = Montserrat({
  weight: "500",
  preload: false,
});

export const metadata = {
  title: "LearnThink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`antialiased bg-slate-950 text-white ${font.className}`}>
        <AuthContextProvider>
          <Navbar />
          <main className="mx-auto max-w-6xl">{children}</main>
        </AuthContextProvider>
      </body>
    </html>
  );
}
