// import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import Navbar from '@/components/Navbar'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Navbar />
//         {children}
//       </body>
//     </html>
//   )
// }


import Navbar from "@/components/Navbar"
import './globals.css'
import { Montserrat } from 'next/font/google'

const font = Montserrat({ 
  weight: "500",
  preload: false
})

export const metadata = {
  title: 'LearnThink',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body className={`antialiased bg-slate-950 text-white ${font.className}`}>
          <Navbar/>

          <main className="mx-auto max-w-6xl">
            {children}
          </main>
        </body>
      </html>
  )
}